In [ ]:
#Mengimport library

import pandas as pd
import numpy as np

In [ ]:
#Memanggil file csv yang akan digunakan

dataset = pd.read_csv('data.csv', header=0)
dataset

warna     bulu makanan kesukaan jenis
0    hitam  panjang           wortel     A
1    putih  panjang           wortel     A
2  cokelat   pendek         kangkung     B
3    hitam   pendek         kangkung     B
4    hitam   gimbal           rumput     C
5  cokelat   gimbal           rumput     A
6  cokelat  panjang           rumput     B
7    putih   pendek           wortel     B
8    putih   pendek         kangkung     C
9  cokelat   gimbal         kangkung     C

In [ ]:
#Mengimport library dan menyimpan fungsinya di dalam variabel

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [ ]:
#Mengubah tipe data menjadi integer
dataset['warna'] = le.fit_transform(dataset['warna'].values)
dataset['bulu'] = le.fit_transform(dataset['bulu'].values)
dataset['makanan kesukaan'] = le.fit_transform(dataset['makanan kesukaan'].values)
dataset['jenis'] = le.fit_transform(dataset['jenis'].values)
dataset

warna  bulu  makanan kesukaan  jenis
0      1     1                 2      0
1      2     1                 2      0
2      0     2                 0      1
3      1     2                 0      1
4      1     0                 1      2
5      0     0                 1      0
6      0     1                 1      1
7      2     2                 2      1
8      2     2                 0      2
9      0     0                 0      2

In [ ]:
#Mengubah dataset menjadi matriks

dataset = dataset.to_numpy()

In [ ]:
#Memanggil file csv yang akan digunakan untuk perbandingan prediksi

dataset2 = pd.read_csv('prediksi.csv', header=0)
dataset2

warna     bulu makanan kesukaan jenis
0   hitam   gimbal           rumput     A
1   putih   pendek           wortel     B
2  coklat  panjang         kangkung     C
3   putih  panjang           rumput     C
4  coklat   gimbal         kangkung     B

In [ ]:
#Mengubah tipe data menjadi integer
dataset2['warna'] = le.fit_transform(dataset2['warna'].values)
dataset2['bulu'] = le.fit_transform(dataset2['bulu'].values)
dataset2['makanan kesukaan'] = le.fit_transform(dataset2['makanan kesukaan'].values)
dataset2['jenis'] = le.fit_transform(dataset2['jenis'].values)
dataset2

warna  bulu  makanan kesukaan  jenis
0      1     0                 1      0
1      2     2                 2      1
2      0     1                 0      2
3      2     1                 1      2
4      0     0                 0      1

In [ ]:
#Mengubah dataset2 menjadi bentuk matriks

dataset2 = dataset2.to_numpy()

In [ ]:
#Melakukan inisialisasi untuk dataset (data training) dan dataset2 (data testing)

data_input, data_label = dataset, dataset
prediksi_input, prediksi_label = dataset2, dataset2
# data_label = dataset
# prediksi_label = dataset2

In [ ]:
#Inisialisasi fungsi DecisonTreeClasifier
from sklearn import tree
model = tree.DecisionTreeClassifier()

In [ ]:
#Menggabungkan dataset

model = model.fit(data_input, data_label)

In [ ]:
#Melakukan perbandingan antara dataset (data) dan dataset2 (prediksi)

hasil_prediksi = model.predict(prediksi_label)
print('Label Sebenarnya')
print(prediksi_label)
print('\nHasil Prediksi')
print(hasil_prediksi)

Label Sebenarnya
[[1 0 1 0]
 [2 2 2 1]
 [0 1 0 2]
 [2 1 1 2]
 [0 0 0 1]]

Hasil Prediksi
[[0 0 1 0]
 [2 2 2 1]
 [0 0 0 2]
 [1 0 1 2]
 [0 0 1 0]]


In [ ]:
#Mengidentifikasi prediksi dan nilai akurasi

prediksi_benar = (hasil_prediksi == prediksi_label).sum()
prediksi_salah = (hasil_prediksi != prediksi_label).sum()
print(f'Prediksi benar : {prediksi_benar} data')
print(f'Prediksi salah : {prediksi_salah} data')
print(f'Nilai Akurasi {prediksi_benar/(prediksi_benar + prediksi_salah)*100}%')

Prediksi benar : 14 data
Prediksi salah : 6 data
Nilai Akurasi 70.0%


In [ ]:
#Membuat grafis visualisasi dari Decision Tree

from sklearn.tree import export_graphviz
export_graphviz(model, out_file="DecisionTree", impurity=False, filled=True)

import graphviz

with open('DecisionTree') as fig:
    dot_graph = fig.read()
    graph = graphviz.Source(dot_graph)

graph.view()

'Source.gv.pdf'