In [ ]:
#Mengimport library
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
#Memanggil file csv yang akan digunakan
dataset = pd.read_csv('data.csv')
dataset

warna     bulu makanan kesukaan jenis
0    hitam  panjang           wortel     A
1    putih  panjang           wortel     A
2  cokelat   pendek         kangkung     B
3    hitam   pendek         kangkung     B
4    hitam   gimbal           rumput     C
5  cokelat   gimbal           rumput     A
6  cokelat  panjang           rumput     B
7    putih   pendek           wortel     B
8    putih   pendek         kangkung     C
9  cokelat   gimbal         kangkung     C

In [ ]:
#Mengimport library
from sklearn.preprocessing import LabelEncoder

In [ ]:
#Menyimpan library ke dalam variabel
le = LabelEncoder()

In [ ]:
#Mengubah tipe data string menjadi integer
dataset['warna'] = le.fit_transform(dataset['warna'].values)
dataset['bulu'] = le.fit_transform(dataset['bulu'].values)
dataset['makanan kesukaan'] = le.fit_transform(dataset['makanan kesukaan'].values)
dataset['jenis'] = le.fit_transform(dataset['jenis'].values)
dataset

warna  bulu  makanan kesukaan  jenis
0      1     1                 2      0
1      2     1                 2      0
2      0     2                 0      1
3      1     2                 0      1
4      1     0                 1      2
5      0     0                 1      0
6      0     1                 1      1
7      2     2                 2      1
8      2     2                 0      2
9      0     0                 0      2

In [ ]:
#Memisahkan data jenis
ind = dataset.drop(['jenis'], axis='columns')
ind

warna  bulu  makanan kesukaan
0      1     1                 2
1      2     1                 2
2      0     2                 0
3      1     2                 0
4      1     0                 1
5      0     0                 1
6      0     1                 1
7      2     2                 2
8      2     2                 0
9      0     0                 0

In [ ]:
#Tipe data jenis dijadikan target klasifikasi
target = dataset['jenis']
target

0    0
1    0
2    1
3    1
4    2
5    0
6    1
7    1
8    2
9    2
Name: jenis, dtype: int64

In [ ]:
#Mengimport library
#Memisahkan data menjadi test dan train
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(ind, target, test_size = 0.25, random_state = 0)

In [ ]:
#Mengimport library
from sklearn.naive_bayes import GaussianNB
#Memanggil fungsi klasifikasi Naive Bayes
modelnb = GaussianNB()
#Memasukkan data training pada fungsi klasifikasi Naive Bayes
nbtrain = modelnb.fit(x_train, y_train)


In [ ]:
#Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 0])

In [ ]:
np.array(y_test)

array([1, 2, 2])

In [ ]:
#Menentukan probabilitas hasil prediksi
nbtrain.predict_proba(x_test)

array([[1.66442562e-04, 9.99833557e-01, 0.00000000e+00],
       [1.66442562e-04, 9.99833557e-01, 0.00000000e+00],
       [9.91831809e-01, 8.16819060e-03, 0.00000000e+00]])

In [ ]:
#Mengimport library
#Mendapatkan confusion matrix (Jumlah prediksi yang salah)
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[0, 0, 0],
       [0, 1, 0],
       [1, 1, 0]])

In [ ]:
#Mengimport library
#Mendapatkan nilai akurasi dengan classification_report
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       0.50      1.00      0.67         1
           2       0.00      0.00      0.00         2

    accuracy                           0.33         3
   macro avg       0.17      0.33      0.22         3
weighted avg       0.17      0.33      0.22         3



/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1308: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1

In [ ]:
#Mengimport library
#Mendapatkan nilai akurasi
from sklearn.metrics import accuracy_score
print(accuracy_score(y_test, y_pred))

0.3333333333333333
